#!/usr/bin/python3

import re
import requests
from bs4 import BeautifulSoup


def process(data):
    for line in data.splitlines():
        if line == '':
            continue

        m = re.search('^0\.0\.0\.0 (.+)', line)
        if m:
            print(m.group(1))


r = requests.get('http://someonewhocares.org/hosts/zero/')
soup = BeautifulSoup(r.text)

for body in soup.find_all(attrs={'class': 'BODY'}):
    # import IPython
    # IPython.embed()
    process(''.join(body.pre.decode_contents()))
