#!/usr/bin/python3

import re
import requests
from bs4 import BeautifulSoup


def parse_host_file(data):
    for line in data.splitlines():
        if line == '':
            continue
        match = re.search('^0\.0\.0\.0 ([^\s]+)', line)
        if match:
            yield match.group(1)


def someonewhocares():
    r = requests.get('http://someonewhocares.org/hosts/zero/')
    r.raise_for_status()

    soup = BeautifulSoup(r.text)
    for body in soup.find_all(attrs={'class': 'BODY'}):
        return body.pre.decode_contents()


def winhelp2002():
    r = requests.get('http://winhelp2002.mvps.org/hosts.txt')
    r.raise_for_status()
    return r.text


providers = [someonewhocares, winhelp2002]


if __name__ == '__main__':
    hosts = set()

    for provider in providers:
        hosts.update(parse_host_file(provider()))

    for host in sorted(hosts):
        print(host)
